---
# Dependencies for IntelliJ IDEA
intellij_dependencies: []
intellij_file_extension: ".tar.gz"
user_home_location: "/home/"
intellij_product_info_dir: "{{ intellij_install_dir }}"
intellij_force: true
